# Sets default memory used for gradle commands.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft & NeoForge Versions
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.180
neo_version_range=[21.1,)
loader_version_range=[4,)

# Mod Properties
mod_id=icraft
mod_name=iCraft
mod_license=MIT
mod_version=1.7.18
mod_group_id=com.icraft
mod_authors=LosTomobri
mod_description=iCraft adds a fully functional smartphone to Minecraft, with chat, camera, marketplace, notes and more apps to explore.

# Parchment Mappings
parchment_mappings_version=2024.11.17
parchment_minecraft_version=1.21.1
